In [1]:
import os
import pandas as pd

In [6]:
files = [f for f in os.listdir() if '.csv' in f and 'val' in f and 'submission' in f]
len(files)

12

In [11]:
sorted(files)

['submission_evaluation_lt_9.csv',
 'submission_evaluation_lvl_10.csv',
 'submission_evaluation_lvl_11.csv',
 'submission_evaluation_lvl_13.csv',
 'submission_evaluation_lvl_14.csv',
 'submission_evaluation_lvl_15.csv',
 'submission_validation_lt_9.csv',
 'submission_validation_lvl_10.csv',
 'submission_validation_lvl_11.csv',
 'submission_validation_lvl_13.csv',
 'submission_validation_lvl_14.csv',
 'submission_validation_lvl_15.csv']

In [12]:
s = []
for file in files:
    s.append(pd.read_csv(file, header = 0))

In [15]:
s = pd.concat(s)

In [16]:
s

,id,F1,F2,F3,F4,F5,F6,F7,F8,F9,...,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28
0,HOBBIES_1_001_CA_1_0.005_validation,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
1,HOBBIES_1_001_CA_2_0.005_validation,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2,HOBBIES_1_001_CA_3_0.005_validation,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
3,HOBBIES_1_001_CA_4_0.005_validation,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,HOBBIES_1_001_TX_1_0.005_validation,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129325,FOODS_3_827_TX_2_0.995_evaluation,2.922,2.884,3.179,3.416,3.844,3.478,3.152,2.995,3.262,...,3.377,3.187,3.730,2.898,4.996,2.936,3.641,3.583,3.303,4.056
129326,FOODS_3_827_TX_3_0.995_evaluation,7.820,8.301,8.624,8.491,9.495,9.446,8.185,8.497,7.765,...,8.502,8.767,9.296,7.892,8.511,12.667,8.153,8.928,8.803,9.228
129327,FOODS_3_827_WI_1_0.995_evaluation,16.864,16.732,17.312,17.193,17.009,16.523,17.627,15.883,17.074,...,17.241,16.973,18.276,16.734,16.306,16.419,16.585,16.679,18.312,19.495
129328,FOODS_3_827_WI_2_0.995_evaluation,8.500,9.187,10.095,10.805,11.635,11.615,13.392,8.737,9.204,...,11.404,10.210,8.993,10.327,10.303,9.444,9.582,11.294,11.091,10.321
129329,FOODS_3_827_WI_3_0.995_evaluation,9.013,8.585,9.275,8.601,8.129,8.303,7.892,9.287,8.450,...,8.658,11.316,9.360,7.690,9.380,9.016,8.594,8.617,8.766,9.909

In [19]:
import zipfile

In [17]:
s.to_csv('submission.csv', index = False)

In [22]:
zipfile.ZipFile('submission.zip', 'w', zipfile.ZIP_DEFLATED).write('submission.csv')